version: '3.8'

services:
  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/reactnative-marketplace
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://reactnative-marketplace:reactnative-marketplace@db
      APP_BASE_URL: https://9f23-187-180-212-135.ngrok-free.app
      JWT_KEY: JWTTESTE
      PORT: 3000
    depends_on:
      - db
    networks:
      - reactnative-marketplace-network
  db:
    image: mongo:5.0.19
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactnative-marketplace
      MONGO_INITDB_ROOT_PASSWORD: reactnative-marketplace
    ports:
      - "27017:27017"
    networks:
      - reactnative-marketplace-network

networks:
  reactnative-marketplace-network:
    name: reactnative-marketplace-network
    external: true
volumes:
  db: